@token = paste-the-accessToken-from-login-here

### Sign up (returns a token straight away)
POST http://localhost:5097/auth/signup
Content-Type: application/json

{
    "name": "Nima Sadeghi",
    "email": "sadeghinima090@gmail.com",
    "password": "Nima@1382",
    "confirmPassword": "Nima@1382"
}

### Log in
POST http://localhost:5097/auth/login
Content-Type: application/json

{
    "email": "sadeghinima090@gmail.com",
    "password": "Nima@1382"
}

### Who am I (requires a token)
GET http://localhost:5097/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzYWRlZ2hpbmltYTA5MEBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImp0aSI6Ijc4ZDg3ZDIyLTEwZWItNDJiOC05NmI5LTBlYTQwMDY4NzVlMiIsIm5iZiI6MTc4NjA1Mzg3MiwiZXhwIjoxNzg2MDU3NDcyLCJpc3MiOiJCb29rc1Byb2plY3QiLCJhdWQiOiJCb29rc1Byb2plY3RDbGllbnQifQ.7GR_hc6tDVJu03k-D0s1HK969vjogkPrJKyIojBBX5
###
POST  http://localhost:5097/auth/refresh
Content-Type: application/json

{
 "RefreshToken" : "u7qntUkk2PsTrnT4EKLtHct9MLCkR9CLzjYGSucaW2SSrA6i4bjO8qJAWLQVwRGBvUTK/KkiBVdwx9td7v7GUw=="
}



###
GET http://localhost:5097/books

###
GET http://localhost:5097/genres


###
GET http://localhost:5097/books?page=1&pageSize=10

###
GET http://localhost:5097/books?page=2&pageSize=10&genreId=14

###
GET http://localhost:5097/books/2

###

Post http://localhost:5097/books
Content-Type:  application/json

{
    "Title": "Test 2",
    "GenreId" : 14,
    "Price" : 40.99,
    "Description": "Nima test 2",
    "PublishedDate": "2010-10-10"
}
###
PUT  http://localhost:5097/books/2
Content-Type:  application/json

{
    "Title": "Test 3",
    "GenreId" : 14,
    "Price" : 20.99,
    "Description": "Nima test 3",
    "PublishedDate": "2010-10-10"
}
###
Post  http://localhost:5097/wishlist/6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJzYWRlZ2hpbmltYTA5MEBnbWFpbC5jb20iLCJyb2xlIjoiQWRtaW4iLCJqdGkiOiJlMmFiMTRjYS01NGI5LTRjYjgtYjRhNC03YTFjNDIzMjQ4MDQiLCJuYmYiOjE3ODY0NjExMzAsImV4cCI6MTc4NjQ2NDczMCwiaXNzIjoiQm9va3NQcm9qZWN0IiwiYXVkIjoiQm9va3NQcm9qZWN0Q2xpZW50In0.u2x0rHAmH0HyUSK_8IvHSvkPMcMzp2uLKCSoZj79eJI

